### ISSUE TITLE
Copied content from Apache 2.0 Licensed Project

### ISSUE THREAD

**Issue by Snooz82** [qahive/robotframework-ExcelDataDriver#1]
Hi,

I am happy that you liked my code and used it.
You are using content from the following project. 
https://github.com/Snooz82/robotframework-datadriver
So you must retain the original copyright and license information in your code.

This project is written under the Apache 2.0 License and requires, that you mark copied Code as Apache 2 Code or write that this is derived from the source project.

Quote:
`... You must retain, in the Source form of any Derivative Works that You distribute, all copyright, patent, trademark, and attribution notices from the Source form of the Work, excluding those notices that do not pertain to any part of the Derivative Works...`

http://www.apache.org/licenses/LICENSE-2.0

i hope you understand this.
Good luck with your work.

Cheers René

**Comment by atthaboon** [comment]
Thanks a lot for your mention. Previous i only put the apache 2.0 under setup.py and thought that it's should be ok.

So i already add the apache license on top of the init file and source file that i derive from.
Please feel free to comment or reopen if still need to update other place.

![image](https://user-images.githubusercontent.com/855604/71970920-20ec3900-323c-11ea-97e6-8bb41a8f1e4d.png)

**Comment by Snooz82** [comment]
It is fine like this.
Thanks!
