### ISSUE TITLE
Several errors on the listener

### ISSUE THREAD

**Issue by joel-oliveira** [qahive/robotframework-ExcelDataDriver#3]
Running the sample project from the documentation, I'm getting these errors:
- Calling method 'start_suite' of listener 'ExcelDataDriver' failed: KeyError: None
- Calling method 'start_test' of listener 'ExcelDataDriver' failed: KeyError: "Verify valid user '${username}'"
- Calling method 'end_test' of listener 'ExcelDataDriver' failed: AttributeError: 'NoneType' object has no attribute 'update_result'

Environment:
- Python 3.7.4 on win32
- Robot Framework 3.2.1
- robotframework-exceldatadriver 1.1.6
- robotframework-seleniumlibrary 4.4.0
- setuptools==41.0.1
- inject==3.3.2
- Pillow==6.2.1
- openpyxl==2.6.2
- selenium>=3.141.0
- jdcal 1.4.1
- et_xmlfile 1.0.1
- urllib3 1.25.9

**Comment by atthaboon** [comment]
Hi @joel-oliveira 
I just update the example script. Plz download update and try again
